## Copyright 2009-2020 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

set(COMPONENT_NAME ospray)

set(COMPONENT_PATH ${INSTALL_DIR_ABSOLUTE})

set(BUILD_OSPRAY_VERSION devel)

ExternalProject_Add(${COMPONENT_NAME}
  PREFIX ${COMPONENT_NAME}
  DOWNLOAD_DIR ${COMPONENT_NAME}
  STAMP_DIR ${COMPONENT_NAME}/stamp
  SOURCE_DIR ${COMPONENT_NAME}/src
  BINARY_DIR ${COMPONENT_NAME}/build
  LIST_SEPARATOR | # Use the alternate list separator
  URL "http://github.com/ospray/ospray/archive/${BUILD_OSPRAY_VERSION}.zip"
  # Build off the OSPRay superbuilds to manage dependencies
  SOURCE_SUBDIR scripts/superbuild/
  CMAKE_ARGS
    -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
    -DCMAKE_INSTALL_PREFIX:PATH=${COMPONENT_PATH}
    -DCMAKE_INSTALL_INCLUDEDIR=${CMAKE_INSTALL_INCLUDEDIR}
    -DCMAKE_INSTALL_LIBDIR=${CMAKE_INSTALL_LIBDIR}
    -DCMAKE_INSTALL_DOCDIR=${CMAKE_INSTALL_DOCDIR}
    -DCMAKE_INSTALL_BINDIR=${CMAKE_INSTALL_BINDIR}
    -DOSPRAY_BUILD_ISA=ALL
    -DINSTALL_DEPENDENCIES=OFF
    -DOSPRAY_CI_EXTRAS=${BUILD_OSPRAY_CI_EXTRAS}
    -DALWAYS_REBUILD=${ALWAYS_REBUILD}
    -DDOWNLOAD_ISPC=${DOWNLOAD_ISPC}
    -DBUILD_RKCOMMON_VERSION=${BUILD_RKCOMMON_VERSION}
    -DDOWNLOAD_TBB=${DOWNLOAD_TBB}
    -DTBB_VERSION=${TBB_VERSION}
    -DBUILD_EMBREE_VERSION=${BUILD_EMBREE_VERSION}
    -DBUILD_EMBREE_FROM_SOURCE=${BUILD_EMBREE_FROM_SOURCE}
    -DBUILD_OIDN=${BUILD_OIDN}
    -DBUILD_OIDN_VERSION=${BUILD_OIDN_VERSION}
    -DBUILD_OIDN_FROM_SOURCE=${BUILD_OIDN_FROM_SOURCE}
    -DBUILD_GLFW=${BUILD_GLFW}
    -DBUILD_OPENVKL_VERSION=${BUILD_OPENVKL_VERSION}
    -DINSTALL_IN_SEPARATE_DIRECTORIES=OFF
  BUILD_COMMAND ${DEFAULT_BUILD_COMMAND}
  INSTALL_COMMAND ""
  BUILD_ALWAYS ${ALWAYS_REBUILD}
)

set(ISPC_PATH "${COMPONENT_PATH}/bin/ispc${CMAKE_EXECUTABLE_SUFFIX}")
set(TBB_PATH "${COMPONENT_PATH}/")

list(APPEND CMAKE_PREFIX_PATH ${COMPONENT_PATH})
string(REPLACE ";" "|" CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH}")
