SET(OSPRAY_LIST_OF_ALREADY_BUILT_COMPONENTS "" CACHE INTERNAL "" FORCE)
SET(OSPRAY_COMPONENTS_ROOT "${PROJECT_SOURCE_DIR}/components" CACHE INTERNAL "" FORCE)

INCLUDE_DIRECTORIES(${OSPRAY_COMPONENTS_ROOT})
