# --------------------------------------------
# GL/GLUT stuff
# --------------------------------------------
IF (APPLE)
	FIND_PACKAGE(GLUT REQUIRED)
	FIND_PACKAGE(OpenGL REQUIRED)
	INCLUDE_DIRECTORIES(${GLUT_INCLUDE_DIR})
message("APPLE: Glut in ${GLUT_INCLUDE_DIR}")
ELSE(APPLE)
	FIND_PATH(GLUT_INCLUDE_DIR GL/glut.h 
		/usr/include # default
$ENV{TACC_FREEGLUT_INC}
		)
  SET (OPENGL_LIBRARY GL)
	INCLUDE_DIRECTORIES(${GLUT_INCLUDE_DIR})
	FIND_PATH(GLUT_LINK_DIR libglut.so
		/usr/lib64 /usr/lib # default
	$ENV{TACC_FREEGLUT_LIB}
		)
	LINK_DIRECTORIES(${GLUT_LINK_DIR})
	FIND_PACKAGE(GLUT REQUIRED)
	SET(GLUT_LIBRARY glut GLU m)
ENDIF(APPLE)

SET(GLUT_LIBRARIES ${GLUT_LIBRARY} ${OPENGL_LIBRARY})
